### ISSUE TITLE
running surrender --yarn cannot find modules

### ISSUE THREAD

**Issue by jacketti** [tiaanduplessis/react-native-surrender#12]
**Describe the bug**
when I run surrender --yarn I get an error about modules.

**To Reproduce**
1. install react-native-surrender using yarn global add...
2. run surrender --yarn

**Expected behavior**
I expect the command to clear Watchman, remove node_modules and clean cache and other goodies

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Macos 10.14.3

**Additional context**
```
➜  app git:(master) ✗ surrender --yarn
module.js:550
    throw err;
    ^

Error: Cannot find module './commands/android'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/username/.config/yarn/global/node_modules/react-native-surrender/index.js:9:25)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)```

**Comment by deadcoder0904** [comment]
Can confirm this issue.

**Comment by deadcoder0904** [comment]
A workaround is using a previous version.

Do `yarn add react-native-surrender@1.2.0` & try `surrender`
